### ISSUE TITLE
Dumb question: how do ratings on a scale of 1-5 map to positive examples?

### ISSUE THREAD

**Issue by zachmayer** [maciejkula/triplet_recommendations_keras#12]
Is any item a user gave a rating considered a positive example?  Or only items they rated as a 5?

**Comment by maciejkula** [comment]
I think in this case you have to decide it yourself: what rating counts as
positive? It's common to say that any rating higher than some threshold
counts as positive; what that is probably depends on your use case.

**Comment by zachmayer** [comment]
And then would I throw away the known, negative ratings that are below that threshold?

**Comment by maciejkula** [comment]
Yes! You could also model rating and implicit feedback jointly, but I
haven't implemented it here.

**Comment by zachmayer** [comment]
Thanks!  Any ideas for modeling them jointly?  One thing I've tried is treating it as a multiclass problem with 6 classes (class 0 = no rating, class 1-5 correspond to ratings).
